"""Create Table Instrument

Revision ID: 65ce7fdff9e5
Revises: 
Create Date: 2024-12-16 02:46:15.391443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ce7fdff9e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_bought', sa.Date(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('maker', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruments')
    # ### end Alembic commands ###
